# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target '全了电动商城' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'ProgressHUD', '~> 2.4'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod ‘UMengUShare/Social/WeChat'
  pod ‘UMengUShare/Social/QQ'
  pod ‘UMengUShare/UI’
  pod 'JPush'
  pod 'AliPay', '~> 2.1.2'
  pod 'MJRefresh','~>3.1.12'
  # Pods for 全了电动商城

end
